### ISSUE TITLE
FATAL ERROR | 大佬帮我看一下

### ISSUE THREAD

**Issue by aeilot** [CLCK0622/Luogu-cpp-programme#1]
```cpp
printf("我翻开历史一查，这历史没有年代。歪歪斜斜的每页上都写着 “我是巨弱” 几个字，我横竖睡不着，仔细看了半夜，才从字缝里看出来，满本上都写着几个字 “@CLCK AK IOI "！");
```

不知道为什么报错。

**Comment by CLCK0622** [comment]
> ```c++
> printf("我翻开历史一查，这历史没有年代。歪歪斜斜的每页上都写着 “我是巨弱” 几个字，我横竖睡不着，仔细看了半夜，才从字缝里看出来，满本上都写着几个字 “@CLCK AK IOI "！");
> ```
> 
> 不知道为什么报错。

1. 后面要用单引号
2. 应该是@Aeilot 打错人当然报错（）

**Comment by CLCK0622** [comment]
> ```c++
> printf("我翻开历史一查，这历史没有年代。歪歪斜斜的每页上都写着 “我是巨弱” 几个字，我横竖睡不着，仔细看了半夜，才从字缝里看出来，满本上都写着几个字 “@CLCK AK IOI "！");
> ```
> 
> 不知道为什么报错。
